# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      postgres:
        image: postgres
        env:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: mysecretpassword
         POSTGRES_DB: forumapi_test
         
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install migrate and test
      run: |
        npm install
        npm run migrate up
        npm run test
      env:
        HOST: localhost
        PORT: 5000
        PGHOST: localhost
        PGPORT: 5432
        PGUSER: postgres
        PGPASSWORD: mysecretpassword
        PGDATABASE: forumapi_test
        PGHOST_TEST: localhost
        PGUSER_TEST: postgres
        PGDATABASE_TEST: forumapi_test
        PGPASSWORD_TEST: mysecretpassword
        PGPORT_TEST: 5432
        ACCESS_TOKEN_KEY: secret
        REFRESH_TOKEN_KEY: terces
        ACCESS_TOKEN_AGE: 3600
